name: mongodb_replica_set

services:
  config1_primary:
    image: mongo:latest
    container_name: config1_primary
    command: mongod --configsvr --port 30001 --replSet config_rs --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
      - "30001:30001"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}

    volumes:
      - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
      - config1_primary_data_db:/data
      - config1_primary_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 30001 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'
      interval: 5s

  config1_replica_1:
    image: mongo:latest
    container_name: config1_replica_1
    command: mongod --configsvr --port 30002 --replSet config_rs --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
      - "30002:30002"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
      - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
      - config1_replica_1_data_db:/data
      - config1_replica_1_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 30002 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'
      interval: 5s

  config1_replica_2:
    image: mongo:latest
    container_name: config1_replica_2
    command: mongod --configsvr --port 30003 --replSet config_rs --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
      - "30003:30003"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
      - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
      - config1_replica_2_data_db:/data
      - config1_replica_2_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 30003 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'
      interval: 5s

  config1_init:
    image: mongo:latest
    restart: no
    extra_hosts:
     - "host.docker.internal:host-gateway"
    depends_on:
      config1_primary:
        condition: service_healthy
      config1_replica_1:
        condition: service_healthy
      config1_replica_2:
        condition: service_healthy
    command: >
      mongosh -u ${MONGODB_ROOT_USERNAME} -p ${MONGODB_ROOT_PASSWORD} --host host.docker.internal --port 30001 /init.js
    volumes:
      - ./initconf.js:/init.js

  shard1_primary:
    image: mongo:latest
    container_name: shard1_primary
    command: mongod --port 10001 --replSet rs1 --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
     - "10001:10001"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
     - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
     - shard1_primary_data_db:/data
     - shard1_primary_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 10001 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'
      interval: 5s

  shard1_replica_1:
    image: mongo:latest
    container_name: shard1_replica_1
    command: mongod --port 10002 --replSet rs1 --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
     - "10002:10002"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
     - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
     - shard1_replica_1_data_db:/data
     - shard1_replica_1_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 10002 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'

  shard1_replica_2:
    image: mongo:latest
    container_name: shard1_replica_2
    command: mongod --port 10003 --replSet rs1 --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
     - "10003:10003"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
     - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
     - shard1_replica_2_data_db:/data
     - shard1_replica_2_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 10003 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'

  shard1_init:
    image: mongo:latest
    restart: no
    extra_hosts:
     - "host.docker.internal:host-gateway"
    depends_on:
      shard1_primary:
        condition: service_healthy
      shard1_replica_1:
        condition: service_healthy
      shard1_replica_2:
        condition: service_healthy
    command: >
      mongosh -u ${MONGODB_ROOT_USERNAME} -p ${MONGODB_ROOT_PASSWORD} --host host.docker.internal --port 10001 /init.js
#    command: >
#      mongosh -u root -p root --host host.docker.internal --port 10001 --eval 'rs.initiate({  _id: "rs0",  members: [    { _id: 0, host: "host.docker.internal:10001" },    { _id: 1, host: "host.docker.internal:10002" },    { _id: 2, host: "host.docker.internal:10003" },  ],});'
    volumes:
      - ./init1.js:/init.js

  shard2_primary:
    image: mongo:latest
    container_name: shard2_primary
    command: mongod --port 20001 --replSet rs2 --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
     - "20001:20001"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
     - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
     - shard2_primary_data_db:/data
     - shard2_primary_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 20001 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'
      interval: 5s

  shard2_replica_1:
    image: mongo:latest
    container_name: shard2_replica_1
    command: mongod --port 20002 --replSet rs2 --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
     - "20002:20002"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
     - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
     - shard2_replica_1_data_db:/data
     - shard2_replica_1_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 20002 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'

  shard2_replica_2:
    image: mongo:latest
    container_name: shard2_replica_2
    command: mongod --port 20003 --replSet rs2 --bind_ip_all --keyFile /data/configdb/keyfile
    ports:
     - "20003:20003"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
     - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
     - shard2_replica_2_data_db:/data
     - shard2_replica_2_data_configdb:/data/configdb
    healthcheck:
      test: 'mongosh --quiet --port 20003 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'

  shard2_init:
    image: mongo:latest
    restart: no
    extra_hosts:
     - "host.docker.internal:host-gateway"
    depends_on:
      shard2_primary:
        condition: service_healthy
      shard2_replica_1:
        condition: service_healthy
      shard2_replica_2:
        condition: service_healthy
    command: >
      mongosh -u ${MONGODB_ROOT_USERNAME} -p ${MONGODB_ROOT_PASSWORD} --host host.docker.internal --port 20001 /init.js
    volumes:
      - ./init2.js:/init.js

  mongos:
    container_name: mongos
    image: mongo:latest
    ports:
      - "27017:27017"
    extra_hosts:
     - "host.docker.internal:host-gateway"
    restart: always
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
     - MONGO_REPLICA_SET_KEY=${MONGO_REPLICA_SET_KEY}
    volumes:
     - ./keyfile.sh:/docker-entrypoint-initdb.d/keyfile.sh
     - mongos_data_db:/data
     - mongos_data_configdb:/data/configdb
    command: mongos --configdb config_rs/host.docker.internal:30001,host.docker.internal:30002,host.docker.internal:30003 --port 27017 --bind_ip_all --keyFile /data/configdb/keyfile
    healthcheck:
      test: 'mongosh --quiet --port 27017 --eval "db.runCommand({ ping: 1 }).ok" | grep 1'

  mongos_init:
    image: mongo:latest
    restart: no
    extra_hosts:
     - "host.docker.internal:host-gateway"
    depends_on:
      mongos:
        condition: service_healthy
    command: >
      mongosh -u ${MONGODB_ROOT_USERNAME} -p ${MONGODB_ROOT_PASSWORD} --host host.docker.internal --port 27017 /init.js
    volumes:
      - ./initmongos.js:/init.js


volumes:
  shard1_primary_data_db:
  shard1_primary_data_configdb:
  shard1_replica_1_data_db:
  shard1_replica_1_data_configdb:
  shard1_replica_2_data_db:
  shard1_replica_2_data_configdb:
  shard2_primary_data_db:
  shard2_primary_data_configdb:
  shard2_replica_1_data_db:
  shard2_replica_1_data_configdb:
  shard2_replica_2_data_db:
  shard2_replica_2_data_configdb:
  config1_primary_data_db:
  config1_primary_data_configdb:
  config1_replica_1_data_db:
  config1_replica_1_data_configdb:
  config1_replica_2_data_db:
  config1_replica_2_data_configdb:
  mongos_data_db:
  mongos_data_configdb:

networks:
  default:
    name: mongodb_replica_set_network
